# Do go benchmark for all days in a matrix
# use fast cpu

name: Benchmark
on: [push]

jobs:
    benchmark:
        runs-on: macos-latest
        strategy:
            matrix:
                day : ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25"]
        steps:
            - uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21
            - name: Run benchmark
              run: |
               cd ${{ github.workspace }}
               if [ ! -d "day${{ matrix.day }}" ]; then
                 exit 0
               fi  
               cd day${{ matrix.day }}
               go test -bench=. -benchmem -benchtime=10s ./...