# Do go benchmark for all days in a matrix

name: Benchmark
on: [push]

jobs:
    benchmark:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.16
            - name: Run benchmark
              run: go test -bench=. -benchmem -benchtime=10s ./...