# Do go benchmark for all days in a matrix
# use fast cpu

name: Benchmark
on: [push]

jobs:
    benchmark:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: 1.21
            - name: Run benchmark
              run: |
               cd ${{ github.workspace }}
               cd day11
               go test -bench=. -benchmem -benchtime=10s ./...